// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz5GdjyHbtf7SBVoQpA1DJ8Ra6POFXNd0',
    appId: '1:663921871682:web:87331e6d9f7e4c7ac9d6db',
    messagingSenderId: '663921871682',
    projectId: 'kasonde-bbuku',
    authDomain: 'kasonde-bbuku.firebaseapp.com',
    storageBucket: 'kasonde-bbuku.firebasestorage.app',
    measurementId: 'G-RND0T8KF5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf1WaEZHll2bAtYHvBW7_11AsShIDJBq8',
    appId: '1:663921871682:android:f5eaedb062175cc1c9d6db',
    messagingSenderId: '663921871682',
    projectId: 'kasonde-bbuku',
    storageBucket: 'kasonde-bbuku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDopvowxgfvHnxxBGw5TsDfxUMEVss6AHI',
    appId: '1:663921871682:ios:0959cb9bbe490f48c9d6db',
    messagingSenderId: '663921871682',
    projectId: 'kasonde-bbuku',
    storageBucket: 'kasonde-bbuku.firebasestorage.app',
    iosBundleId: 'com.breadoflife.churchCms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDopvowxgfvHnxxBGw5TsDfxUMEVss6AHI',
    appId: '1:663921871682:ios:0959cb9bbe490f48c9d6db',
    messagingSenderId: '663921871682',
    projectId: 'kasonde-bbuku',
    storageBucket: 'kasonde-bbuku.firebasestorage.app',
    iosBundleId: 'com.breadoflife.churchCms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz5GdjyHbtf7SBVoQpA1DJ8Ra6POFXNd0',
    appId: '1:663921871682:web:e350e0b43c53dd8fc9d6db',
    messagingSenderId: '663921871682',
    projectId: 'kasonde-bbuku',
    authDomain: 'kasonde-bbuku.firebaseapp.com',
    storageBucket: 'kasonde-bbuku.firebasestorage.app',
    measurementId: 'G-YD92L04P79',
  );
}
